Repository KepplerDevelopers/keppler_core, pull requests merged in 2018-10, with the labels that each got.

#413 Listo select de idioma
  app/assets/images/admin/en.png
  app/assets/images/admin/es.png
  app/assets/stylesheets/admin/components/navigation/_navbar.scss
  app/controllers/admin/settings_controller.rb
  app/controllers/application_controller.rb
  app/policies/setting_policy.rb
  app/views/admin/layouts/_navigation.html.haml
  app/views/admin/layouts/_sidebar.html.haml
  app/views/admin/meta_tags/index.html.haml
  app/views/admin/roles/index.html.haml
  app/views/admin/scripts/index.html.haml
  app/views/admin/settings/_form.html.haml
  app/views/admin/settings/edit.html.haml
  app/views/admin/settings/fields/_appearance.html.haml
  app/views/admin/users/index.html.haml
  config/application.rb
  config/locales/en.yml
  config/locales/es.yml
  config/menu.yml
  config/routes.rb
  config/settings.yml
  config/sitemap.rb
  db/migrate/20160201210520_create_appearances.rb
  db/migrate/20180925184813_create_osginvwbqg_keppler_capsules_posts.keppler_capsules.rb
  db/migrate/20180925185524_drop_mohqricnpq_keppler_capsules_posts.keppler_capsules.rb
  db/seeds.rb
  rockets/keppler_capsules/app/views/keppler_capsules/admin/capsules/index.html.haml
  rockets/keppler_capsules/app/views/keppler_capsules/admin/layouts/_navigation.html.haml
  rockets/keppler_capsules/db/migrate/20180925184804_create_osginvwbqg_keppler_capsules_posts.rb
  rockets/keppler_capsules/db/migrate/20180925185520_drop_mohqricnpq_keppler_capsules_posts.rb
  rockets/keppler_capsules/lib/generators/keppler_capsule_scaffold/templates/views/index.html.haml
  rockets/keppler_frontend/app/controllers/keppler_frontend/application_controller.rb
  rockets/keppler_frontend/app/views/keppler_frontend/admin/callback_functions/index.html.haml
  rockets/keppler_frontend/app/views/keppler_frontend/admin/functions/index.html.haml
  rockets/keppler_frontend/app/views/keppler_frontend/admin/layouts/_navigation.html.haml
  rockets/keppler_frontend/app/views/keppler_frontend/admin/partials/index.html.haml
  rockets/keppler_frontend/app/views/keppler_frontend/admin/themes/index.html.haml
  rockets/keppler_frontend/app/views/keppler_frontend/admin/views/index.html.haml
  rockets/keppler_languages/app/views/keppler_languages/admin/languages/index.html.haml
  rockets/keppler_languages/app/views/keppler_languages/admin/layouts/_navigation.html.haml
Labels: Patch, requerimiento

#414 Colocado un mensaje en el preloade
  app/assets/stylesheets/admin/pages/_preloader.scss
  app/views/admin/layouts/_preloader.html.haml
  config/locales/en.yml
  config/locales/es.yml
Labels: Patch, requerimiento

#418 Mejoras en el editor de interfaces graficas
  rockets/keppler_frontend/app/assets/html/keppler_frontend/app/bootstrap/bstp-columns-12.html
  rockets/keppler_frontend/app/assets/html/keppler_frontend/app/bootstrap/bstp-columns-2.html
  rockets/keppler_frontend/app/assets/html/keppler_frontend/app/bootstrap/bstp-columns-3.html
  rockets/keppler_frontend/app/assets/html/keppler_frontend/app/bootstrap/bstp-columns-4.html
  rockets/keppler_frontend/app/assets/html/keppler_frontend/app/bootstrap/bstp-columns-6.html
  rockets/keppler_frontend/app/assets/html/keppler_frontend/app/bootstrap/bstp-navbar.html
  rockets/keppler_frontend/app/assets/javascripts/keppler_frontend/app/grapes/grapes-editor.js
  rockets/keppler_frontend/app/assets/javascripts/keppler_frontend/app/grapes/grapes.js
  rockets/keppler_frontend/app/assets/stylesheets/keppler_frontend/app/grapes/grapes-custom.scss
  rockets/keppler_frontend/app/controllers/keppler_frontend/concerns/grapesjs.rb
Labels: Patch, mejora

#455 Tema daña el css del Editor live
  rockets/keppler_frontend/app/assets/javascripts/keppler_frontend/app/grapes/grapes-editor.js
  rockets/keppler_frontend/app/assets/javascripts/keppler_frontend/app/grapes/grapes.js
  rockets/keppler_frontend/app/views/layouts/keppler_frontend/app/layouts/_keppler_editor.html.haml
  rockets/keppler_frontend/app/views/layouts/keppler_frontend/app/layouts/application.html.erb
  rockets/keppler_frontend/config/themes.yml
Labels: Patch, bug

#467 Pdrowr/464/helpers bug
  rockets/keppler_frontend/app/helpers/keppler_frontend/app/frontend_helper.rb
  rockets/keppler_frontend/app/models/keppler_frontend/concerns/partials/helper_file.rb
Labels: bug

#462 Pdrowr/457/bug partials
  rockets/keppler_frontend/app/views/keppler_frontend/admin/views/_editor_views.html.haml
  rockets/keppler_frontend/app/views/keppler_frontend/app/partials/_devise_login.html.erb
Labels: bug

#471 Pdrowr/469/default languages
  app/controllers/app/app_controller.rb
  rockets/keppler_frontend/app/controllers/keppler_frontend/app/app_controller.rb
Labels: Patch
