Repository KepplerDevelopers/keppler_core, pull requests merged in 2018-07, with the labels that each got.

#283 changed keppler admin default email
  db/seeds.rb
Labels: Patch, cambio, maxima prioridad

#282 fixed settings customize bug
  app/assets/stylesheets/admin/pages/_devise.scss
Labels: Patch, bug, maxima prioridad

#310 Mostrar configuración debajo de los rockets
  app/views/admin/layouts/_sidebar.html.haml
  config/menu.yml
Labels: Patch

#308 Anyelopetit/259/keppler file input only
  app/assets/javascripts/admin/bootstrap-file-input/fileinput.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/LANG.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/ar.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/az.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/bg.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/ca.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/cr.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/cs.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/da.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/de.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/el.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/es.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/et.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/fa.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/fi.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/fr.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/gl.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/hu.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/id.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/it.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/ja.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/ka.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/kr.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/kz.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/lt.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/nl.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/no.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/pl.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/pt-BR.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/pt.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/ro.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/ru.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/sk.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/sl.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/sv.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/th.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/tr.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/uk.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/vi.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/zh-TW.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/zh.js
  app/assets/javascripts/admin/bootstrap-file-input/plugins/piexif.js
  app/assets/javascripts/admin/bootstrap-file-input/plugins/piexif.min.js
  app/assets/javascripts/admin/bootstrap-file-input/plugins/purify.js
  app/assets/javascripts/admin/bootstrap-file-input/plugins/purify.min.js
  app/assets/javascripts/admin/bootstrap-file-input/plugins/sortable.js
  app/assets/javascripts/admin/bootstrap-file-input/plugins/sortable.min.js
  app/assets/stylesheets/admin/application.scss
  app/assets/stylesheets/admin/bootstrap-file-input/fileinput-rtl.scss
  app/assets/stylesheets/admin/bootstrap-file-input/fileinput.scss
  app/assets/stylesheets/admin/bootstrap-file-input/themes/explorer-fa/theme.scss
  app/assets/stylesheets/admin/bootstrap-file-input/themes/explorer-fas/theme.scss
  app/assets/stylesheets/admin/bootstrap-file-input/themes/explorer/theme.scss
  app/inputs/keppler_file_input.rb
  app/models/front.rb
Labels: Patch, mejora
