Repository KepplerDevelopers/keppler_core, pull requests merged in 2018-09, with the labels that each got.

#378 Modulo de SEO
  app/assets/javascripts/admin/code_editor.js
  app/controllers/admin/seos_controller.rb
  app/models/seo.rb
  app/policies/seo_policy.rb
  app/views/admin/layouts/_head.html.haml
  app/views/admin/seos/robots.html.haml
  app/views/admin/seos/sitemap.html.haml
  config/locales/en.yml
  config/locales/es.yml
  config/menu.yml
  config/permissions.yml
  config/routes.rb
  config/sitemap.rb
  db/migrate/20180904144238_create_seos.rb
  public/robots.txt
Labels: cambio, mejora

#380 Administar roles en modulos anidados
  app/assets/javascripts/admin/adminlte.js
  app/controllers/application_controller.rb
  app/helpers/admin_helper.rb
  app/models/role.rb
  app/models/user.rb
  app/policies/application_policy.rb
  app/views/admin/layouts/_sidebar.html.haml
  app/views/admin/permissions/add.html.haml
  config/locales/es.yml
  config/menu.yml
  config/permissions.yml
  rockets/keppler_capsules/config/menu.yml
  rockets/keppler_capsules/config/permissions.yml
  rockets/keppler_frontend/config/menu.yml
  rockets/keppler_frontend/config/permissions.yml
  rockets/keppler_languages/config/permissions.yml
  test/run.sh
Labels: Patch, mejora

#391 Destroy multiple in roles module
  app/controllers/admin/roles_controller.rb
  app/views/admin/roles/_listing.html.haml
Labels: Patch, bug

#397 Actualizar diseño de las capsulas
  app/controllers/admin/admin_controller.rb
  rockets/keppler_capsules/lib/generators/keppler_capsule_scaffold/templates/views/_listing.html.haml
  rockets/keppler_capsules/lib/generators/keppler_capsule_scaffold/templates/views/index.html.haml
Labels: Patch, requerimiento
