Repository KepplerDevelopers/keppler_core, pull requests merged in 2018-08, with the labels that each got.

#311 Anyelopetit/249/load data
  app/assets/javascripts/admin/main.coffee
  app/controllers/concerns/object_query.rb
  app/models/concerns/downloadable.rb
  app/models/concerns/uploadable.rb
  app/views/admin/meta_tags/_index_show.html.haml
  app/views/admin/meta_tags/index.html.haml
  app/views/admin/roles/_index_show.html.haml
  app/views/admin/scripts/_index_show.html.haml
  app/views/admin/scripts/index.html.haml
  app/views/admin/users/_index_show.html.haml
  lib/generators/keppler_scaffold/templates/views/_index_show.haml
  lib/generators/keppler_scaffold/templates/views/index.haml
Labels: Patch, bug, maxima prioridad

#318 Anyelopetit/317/select multiple
  app/assets/javascripts/vue_admin/index.js
  app/controllers/concerns/object_query.rb
  app/views/admin/meta_tags/_listing.html.haml
Labels: Patch, bug, maxima prioridad

#319 Anyelopetit/315/bug social account
  app/models/setting.rb
Labels: Patch, cambio, maxima prioridad

#309 Anyelopetit/286/messages badge
  app/views/admin/layouts/_preloader.html.haml
  app/views/admin/layouts/_sidebar.html.haml
Labels: Patch, mejora

#320 Anyelopetit/314/order position desc
  app/controllers/admin/meta_tags_controller.rb
  app/controllers/admin/roles_controller.rb
  app/controllers/admin/scripts_controller.rb
  lib/generators/keppler_scaffold/templates/controllers/controller.rb
Labels: Patch, cambio, maxima prioridad

#324 Implementado turbolinks
  app/assets/javascripts/admin/application.coffee
  app/assets/javascripts/admin/bootstrap-file-input/locales/ar.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/az.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/bg.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/ca.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/cr.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/cs.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/da.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/de.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/el.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/et.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/fa.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/fi.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/fr.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/gl.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/hu.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/id.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/it.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/ja.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/ka.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/kr.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/kz.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/lt.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/nl.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/no.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/pl.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/pt-BR.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/pt.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/ro.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/ru.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/sk.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/sl.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/sv.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/th.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/tr.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/uk.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/vi.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/zh-TW.js
  app/assets/javascripts/admin/bootstrap-file-input/locales/zh.js
  app/assets/javascripts/admin/dropdown_top.js
  app/assets/javascripts/admin/img_preview.js
  app/assets/javascripts/admin/main.coffee
  app/assets/javascripts/admin/preview_template.js
  app/assets/javascripts/admin/sidebar.js
  app/assets/javascripts/admin/sort.coffee
  app/assets/javascripts/admin/swal.js
  app/assets/javascripts/admin/switch.js
  app/assets/javascripts/admin/tooltips.coffee
  app/assets/javascripts/vue_admin/index.js
  app/assets/stylesheets/admin/pages/_index.scss
  app/controllers/admin/scripts_controller.rb
  app/views/admin/customizes/index.html.haml
  app/views/admin/layouts/_head.html.haml
  app/views/admin/meta_tags/index.html.haml
  app/views/admin/roles/index.html.haml
  app/views/admin/scripts/_listing.html.haml
  app/views/admin/scripts/index.html.haml
  app/views/admin/users/index.html.haml
  config/routes.rb
  lib/generators/keppler_scaffold/templates/views/index.haml
Labels: Patch, mejora

#327 Anyelopetit/249/data csv
  app/controllers/concerns/object_query.rb
Labels: Patch, bug, maxima prioridad

#354 Solved Destroy multiple Bugs
  app/assets/javascripts/vue_admin/index.js
  app/controllers/admin/users_controller.rb
  app/views/admin/users/_listing.html.haml
  db/migrate/20180827154647_add_position_to_users_table.rb
Labels: bug

#353 Solved partials bugs
  db/seeds.rb
  rockets/keppler_frontend/app/controllers/keppler_frontend/admin/partials_controller.rb
  rockets/keppler_frontend/app/models/keppler_frontend/callback_function.rb
  rockets/keppler_frontend/app/models/keppler_frontend/concerns/partials/helper_file.rb
  rockets/keppler_frontend/app/models/keppler_frontend/concerns/string_actions.rb
  rockets/keppler_frontend/app/models/keppler_frontend/partial.rb
  rockets/keppler_frontend/app/views/keppler_frontend/admin/partials/_listing.html.haml
  rockets/keppler_frontend/app/views/keppler_frontend/admin/partials/index.html.haml
  rockets/keppler_frontend/config/locales/en.yml
  rockets/keppler_frontend/config/locales/es.yml
  rockets/keppler_frontend/config/partials.yml
Labels: bug

#368 Pdrowr/363/pundit
  app/controllers/admin/admin_controller.rb
  app/controllers/application_controller.rb
Labels: mejora
